import { PrismaClient } from "@prisma/client";
import { hash } from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 بدء عملية التهيئة...");

  // Admin user (default: username=abud, password=abud ─ override via env)
  const adminUsername = process.env.ADMIN_USERNAME || "abud";
  const adminEmail = process.env.ADMIN_EMAIL || "abud@abud.fun";
  const adminPassword = process.env.ADMIN_PASSWORD || "abud";
  const hashedPassword = await hash(adminPassword, 12);

  const existingAdmin = await prisma.adminUser.findFirst({
    where: { OR: [{ username: adminUsername }, { email: adminEmail }] },
  });
  if (existingAdmin) {
    await prisma.adminUser.update({
      where: { id: existingAdmin.id },
      data: { username: adminUsername, email: adminEmail, password: hashedPassword, name: "Abud" },
    });
  } else {
    await prisma.adminUser.create({
      data: { username: adminUsername, email: adminEmail, password: hashedPassword, name: "Abud" },
    });
  }
  console.log(`✅ Admin: ${adminUsername} / ${adminEmail}`);

  // Product categories
  const [catTools, catCourses, catTemplates, catServices] = await Promise.all([
    prisma.productCategory.upsert({
      where: { slug: "tools" },
      update: {},
      create: { name: "أدوات رقمية", slug: "tools" },
    }),
    prisma.productCategory.upsert({
      where: { slug: "courses" },
      update: {},
      create: { name: "كورسات", slug: "courses" },
    }),
    prisma.productCategory.upsert({
      where: { slug: "templates" },
      update: {},
      create: { name: "قوالب", slug: "templates" },
    }),
    prisma.productCategory.upsert({
      where: { slug: "services" },
      update: {},
      create: { name: "خدمات", slug: "services" },
    }),
  ]);
  console.log("✅ تم إنشاء تصنيفات المنتجات");

  // Products
  await Promise.all([
    prisma.product.upsert({
      where: { slug: "notion-dashboard-arabic" },
      update: {},
      create: {
        title: "لوحة Notion العربية الشاملة",
        slug: "notion-dashboard-arabic",
        shortDesc: "لوحة تحكم Notion باللغة العربية لإدارة المشاريع والمهام",
        description: "لوحة تحكم Notion كاملة باللغة العربية لإدارة المشاريع والمهام والأهداف بطريقة احترافية",
        price: 199,
        oldPrice: 350,
        coverImage: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800",
        status: "active",
        featured: true,
        categoryId: catTemplates.id,
      },
    }),
    prisma.product.upsert({
      where: { slug: "nextjs-saas-starter" },
      update: {},
      create: {
        title: "قالب Next.js SaaS الاحترافي",
        slug: "nextjs-saas-starter",
        shortDesc: "قالب متكامل لبناء تطبيقات SaaS",
        description: "قالب متكامل لبناء تطبيقات SaaS بـ Next.js 14 و Prisma و Stripe مع لوحة تحكم كاملة",
        price: 499,
        oldPrice: 799,
        coverImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800",
        status: "active",
        featured: true,
        categoryId: catTemplates.id,
      },
    }),
    prisma.product.upsert({
      where: { slug: "ai-prompt-pack-arabic" },
      update: {},
      create: {
        title: "حزمة برومبت الذكاء الاصطناعي بالعربي",
        slug: "ai-prompt-pack-arabic",
        shortDesc: "أكثر من 500 برومبت احترافي",
        description: "أكثر من 500 برومبت احترافي للعمل مع ChatGPT و Midjourney و Claude",
        price: 149,
        oldPrice: 299,
        coverImage: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800",
        status: "active",
        featured: false,
        categoryId: catTools.id,
      },
    }),
    prisma.product.upsert({
      where: { slug: "freelance-mastery-course" },
      update: {},
      create: {
        title: "كورس الفريلانس الاحترافي",
        slug: "freelance-mastery-course",
        shortDesc: "تعلم كيف تبني مشروعك الحر من الصفر",
        description: "تعلم كيف تبني مشروعك الحر من الصفر وتحقق دخلاً شهرياً ثابتاً بالدولار",
        price: 299,
        oldPrice: 599,
        coverImage: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800",
        status: "active",
        featured: true,
        categoryId: catCourses.id,
      },
    }),
    prisma.product.upsert({
      where: { slug: "professional-website-development-2026" },
      update: {},
      create: {
        title: "تطوير موقع احترافي 2026",
        slug: "professional-website-development-2026",
        shortDesc: "موقع ويب احترافي بأحدث التقنيات - Next.js 14، SEO سريع، متوافق مع الجوال",
        description: "نطور لك موقع ويب احترافي بالكامل: تصميم عصري، SEO متقدم، سرعة فائقة، لوحة تحكم، دعم فني شهر كامل",
        price: 5000,
        oldPrice: 7000,
        coverImage: "https://images.unsplash.com/photo-1467232004585-a2713464baa5?w=800",
        status: "active",
        featured: true,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 7-14 يوم عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "telegram-bot-development-service" },
      update: {},
      create: {
        title: "بوت تيليجرام متقدم",
        slug: "telegram-bot-development-service",
        shortDesc: "بوت تيليجرام احترافي للتجارة الإلكترونية، خدمة العملاء، أو أتمتة الأعمال",
        description: "نبرمج بوت تيليجرام متكامل: واجهة تفاعلية، ربط بقواعد البيانات، دفعات، إشعارات، لوحة تحكم",
        price: 3500,
        oldPrice: 5000,
        coverImage: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800",
        status: "active",
        featured: true,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 5-10 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "business-automation-service" },
      update: {},
      create: {
        title: "أتمتة الأعمال المتكاملة",
        slug: "business-automation-service",
        shortDesc: "وفر 20 ساعة أسبوعياً عبر أتمتة العمليات المتكررة بـ n8n أو Zapier",
        description: "نؤتمت عملك بالكامل: إدخال البيانات، إرسال الإيميلات، إدارة العملاء، تقارير تلقائية، تكامل التطبيقات",
        price: 4000,
        oldPrice: 6000,
        coverImage: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 10-15 يوم عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "cybersecurity-protection-service" },
      update: {},
      create: {
        title: "حماية وأمن سيبراني",
        slug: "cybersecurity-protection-service",
        shortDesc: "تأمين موقعك أو تطبيقك من الهجمات الإلكترونية بـ Cloudflare و Firewall متقدم",
        description: "نؤمن موقعك بالكامل: حماية من DDoS، SSL، Firewall، مراجعة أمنية، تحديثات أمنية، مراقبة 24/7",
        price: 3000,
        oldPrice: 4500,
        coverImage: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800",
        status: "active",
        featured: true,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم الفوري + المراقبة مستمرة",
      },
    }),
    prisma.product.upsert({
      where: { slug: "ai-tools-integration-service" },
      update: {},
      create: {
        title: "تكامل أدوات الذكاء الاصطناعي",
        slug: "ai-tools-integration-service",
        shortDesc: "دمج Claude 3.5 أو ChatGPT في موقعك أو تطبيقك لتوفير الوقت وزيادة الإنتاجية",
        description: "نكامل أدوات AI في عملك: ChatGPT API، Claude، تحليل البيانات، توليد المحتوى، دعم العملاء التلقائي",
        price: 4500,
        oldPrice: 6500,
        coverImage: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 7-12 يوم عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "custom-website-development" },
      update: {},
      create: {
        title: "تطوير مواقع مخصصة",
        slug: "custom-website-development",
        shortDesc: "مواقع ويب احترافية باستخدام Next.js مع تحسين SEO وأداء فائق",
        description: "نطور موقعك بالكامل: تصميم متجاوب، SEO متقدم، أداء عالي، لوحة تحكم، دعم فني 3 شهور",
        price: 1500,
        oldPrice: 2500,
        coverImage: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800",
        status: "active",
        featured: true,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 5-10 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "ai-chatbot-integration" },
      update: {},
      create: {
        title: "تكامل روبوتات الدردشة الذكية",
        slug: "ai-chatbot-integration",
        shortDesc: "ربط ChatGPT و Claude في موقعك لخدمة العملاء وتوليد العملاء",
        description: "نكامل روبوتات ذكية: OpenAI API، Claude، تدريب مخصص، flows محادثة، تحليلات",
        price: 1200,
        oldPrice: 2000,
        coverImage: "https://images.unsplash.com/photo-1531746790737-562ea21961ca?w=800",
        status: "active",
        featured: true,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 3-7 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "telegram-bot-development" },
      update: {},
      create: {
        title: "تطوير بوتات تيليجرام",
        slug: "telegram-bot-development",
        shortDesc: "بوتات تيليجرام مخصصة للأتمتة والتسويق وخدمة العملاء",
        description: "نبرمج بوتك بالكامل: وظائف مخصصة، لوحة تحكم، deployment، دليل استخدام، تحديثات",
        price: 800,
        oldPrice: 1500,
        coverImage: "https://images.unsplash.com/photo-1611224923853-80b023be02b1?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 2-5 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "vps-setup-management" },
      update: {},
      create: {
        title: "إعداد وإدارة VPS",
        slug: "vps-setup-management",
        shortDesc: "إعداد خادم VPS كامل مع الأمان والأداء والمراقبة",
        description: "نجهز سيرفرك: إعداد النظام، حماية، تحسين الأداء، مراقبة، backup، دعم فني",
        price: 600,
        oldPrice: 1000,
        coverImage: "https://images.unsplash.com/photo-1558494949-ef010cbcc31c?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم الفوري + دعم مستمر",
      },
    }),
    prisma.product.upsert({
      where: { slug: "custom-online-tools" },
      update: {},
      create: {
        title: "تطوير أدوات عبر الإنترنت",
        slug: "custom-online-tools",
        shortDesc: "أدوات ويب مخصصة: حاسبات، مولدات، محولات، أنظمة متخصصة",
        description: "نصمم أدواتك: واجهة مستخدم، منطق برمجي، hosting، دليل استخدام، تحديثات",
        price: 1000,
        oldPrice: 1800,
        coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 3-7 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "ai-automation-systems" },
      update: {},
      create: {
        title: "أنظمة أتمتة بالذكاء الاصطناعي",
        slug: "ai-automation-systems",
        shortDesc: "أتمتة العمليات التجارية باستخدام AI لزيادة الكفاءة",
        description: "نؤتمت أعمالك: workflows ذكية، تكامل APIs، تحليل البيانات، تقارير تلقائية",
        price: 1500,
        oldPrice: 2500,
        coverImage: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800",
        status: "active",
        featured: true,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 5-10 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "ecommerce-store-setup" },
      update: {},
      create: {
        title: "إعداد متاجر إلكترونية",
        slug: "ecommerce-store-setup",
        shortDesc: "متاجر Shopify/WooCommerce مخصصة مع الدفع والشحن",
        description: "نجهز متجرك: تصميم مخصص، إمدادات المنتجات، بوابات الدفع، تكامل الشحن، تدريب",
        price: 2000,
        oldPrice: 3500,
        coverImage: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800",
        status: "active",
        featured: true,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 7-14 يوم عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "seo-optimization" },
      update: {},
      create: {
        title: "تحسين SEO والأداء",
        slug: "seo-optimization",
        shortDesc: "مراجعة وتحسين SEO تقني لتحسين ترتيب محركات البحث",
        description: "نحسن موقعك: SEO audit، تحسين الأداء، Core Web Vitals، structured data، تقارير",
        price: 1000,
        oldPrice: 1800,
        coverImage: "https://images.unsplash.com/photo-1618419151362-5b555c8c1c9c?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 3-5 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "saas-prototype" },
      update: {},
      create: {
        title: "نماذج SaaS أولية",
        slug: "saas-prototype",
        shortDesc: "بناء MVP لتطبيقات SaaS مع الميزات الأساسية",
        description: "نبني MVP: core features، user auth، database، payment integration، deployment",
        price: 3000,
        oldPrice: 5000,
        coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
        status: "active",
        featured: true,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 10-20 يوم عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "api-integration" },
      update: {},
      create: {
        title: "تكامل APIs وخدمات الجهات الخارجية",
        slug: "api-integration",
        shortDesc: "ربط APIs وتكاملات مخصصة لأنظمة العمل",
        description: "نكامل أنظمتك: REST APIs، third-party services، data sync، documentation، testing",
        price: 1200,
        oldPrice: 2000,
        coverImage: "https://images.unsplash.com/photo-1558494949-ef010cbcc31c?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 3-7 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "ai-content-system" },
      update: {},
      create: {
        title: "نظام توليد المحتوى بالذكاء الاصطناعي",
        slug: "ai-content-system",
        shortDesc: "أدوات إنشاء محتوى تلقائي للمدونات والسوشيال ميديا",
        description: "نصمم نظامك: content generator، templates، scheduling، AI integration، analytics",
        price: 1800,
        oldPrice: 3000,
        coverImage: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 5-10 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "custom-dashboard" },
      update: {},
      create: {
        title: "لوحات تحكم مخصصة",
        slug: "custom-dashboard",
        shortDesc: "لوحات تحكم تفاعلية لتحليل البيانات والمراقبة",
        description: "نبني dashboardك: data visualization، real-time updates، charts، reports، export",
        price: 2000,
        oldPrice: 3500,
        coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 7-14 يوم عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "website-security" },
      update: {},
      create: {
        title: "تأمين وحماية المواقع",
        slug: "website-security",
        shortDesc: "فحص أمني شامل وتطبيق إجراءات الحماية",
        description: "نؤمن موقعك: security audit، SSL، firewall، monitoring، backup، incident response",
        price: 1000,
        oldPrice: 1800,
        coverImage: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 3-5 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "ai-prompt-engineering" },
      update: {},
      create: {
        title: "هندسة Prompts للذكاء الاصطناعي",
        slug: "ai-prompt-engineering",
        shortDesc: "تصميم prompts محسّنة لتحسين أداء أدوات AI",
        description: "نصمم promptsك: prompt library، optimization techniques، testing، documentation، training",
        price: 800,
        oldPrice: 1500,
        coverImage: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 2-4 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "custom-wordpress" },
      update: {},
      create: {
        title: "تطوير WordPress مخصص",
        slug: "custom-wordpress",
        shortDesc: "قوالب وإضافات WordPress مخصصة مع وظائف متقدمة",
        description: "نطور WordPressك: custom theme، plugins، functionality، optimization، training",
        price: 1500,
        oldPrice: 2500,
        coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 5-10 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "database-optimization" },
      update: {},
      create: {
        title: "تصميم وتحسين قواعد البيانات",
        slug: "database-optimization",
        shortDesc: "تصميم قواعد بيانات فعالة وتحسين الأداء",
        description: "نحسن قاعدة بياناتك: schema design، optimization، indexing، performance tuning، documentation",
        price: 1200,
        oldPrice: 2000,
        coverImage: "https://images.unsplash.com/photo-1558494949-ef010cbcc31c?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 3-7 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "mobile-app-prototype" },
      update: {},
      create: {
        title: "نماذج تطبيقات موبايل",
        slug: "mobile-app-prototype",
        shortDesc: "نماذج أولية لتطبيقات الموبايل للاختبار والتمويل",
        description: "نبني prototypeك: React Native/Flutter، core features، UI/UX، deployment guide",
        price: 2500,
        oldPrice: 4000,
        coverImage: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 10-15 يوم عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "email-automation" },
      update: {},
      create: {
        title: "أتمتة التسويق البريدي",
        slug: "email-automation",
        shortDesc: "أنظمة إيميل أتمتة للتسويق والمتابعة",
        description: "نؤتمت إيميلاتك: email sequences، templates، automation flows، analytics، integration",
        price: 800,
        oldPrice: 1500,
        coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 3-5 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "custom-search-system" },
      update: {},
      create: {
        title: "أنظمة بحث متقدمة",
        slug: "custom-search-system",
        shortDesc: "بحث متقدم مع filters وautocomplete ونتائج ذكية",
        description: "نبني بحثك: advanced search، filters، autocomplete، AI results، analytics، admin panel",
        price: 1500,
        oldPrice: 2500,
        coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 5-10 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "video-editing-tech" },
      update: {},
      create: {
        title: "مونتاج فيديو للمحتوى التقني",
        slug: "video-editing-tech",
        shortDesc: "مونتاج احترافي للفيديوهات التعليمية والدعائية",
        description: "نحرر فيديوهاتك: professional editing، thumbnails، captions، effects، optimization",
        price: 300,
        oldPrice: 500,
        coverImage: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800",
        status: "active",
        featured: false,
        purchaseType: "instant",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 1-3 أيام",
      },
    }),
    prisma.product.upsert({
      where: { slug: "ai-image-generation" },
      update: {},
      create: {
        title: "توليد الصور بالذكاء الاصطناعي",
        slug: "ai-image-generation",
        shortDesc: "صور مخصصة بالذكاء الاصطناعي للعلامة التجارية والتسويق",
        description: "نولد صورك: custom AI images، style guide، prompts، image library، commercial rights",
        price: 800,
        oldPrice: 1500,
        coverImage: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 2-4 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "custom-form-builder" },
      update: {},
      create: {
        title: "بناء نماذج ديناميكية",
        slug: "custom-form-builder",
        shortDesc: "نماذج تفاعلية مع validation وتكاملات",
        description: "نبني نماذجك: dynamic forms، validation، calculations، database integration، analytics",
        price: 1200,
        oldPrice: 2000,
        coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 3-7 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "performance-monitoring" },
      update: {},
      create: {
        title: "إعداد مراقبة الأداء",
        slug: "performance-monitoring",
        shortDesc: "مراقبة شاملة للتطبيقات مع تنبيهات وتقارير",
        description: "نراقب أدائك: monitoring dashboard، alerts، performance metrics، uptime tracking، reports",
        price: 800,
        oldPrice: 1500,
        coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 2-4 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "custom-cms" },
      update: {},
      create: {
        title: "تطوير CMS مخصص",
        slug: "custom-cms",
        shortDesc: "نظام إدارة محتوى مخصص للاحتياجات الخاصة",
        description: "نطوير CMSك: custom functionality، user roles، content types، plugins، training",
        price: 3000,
        oldPrice: 5000,
        coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 10-20 يوم عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "ai-recommendation-system" },
      update: {},
      create: {
        title: "نظام توصيات بالذكاء الاصطناعي",
        slug: "ai-recommendation-system",
        shortDesc: "محرك توصيات للتجارة الإلكترونية والمحتوى",
        description: "نبني توصياتك: recommendation algorithm، A/B testing، analytics، personalization، integration",
        price: 2500,
        oldPrice: 4000,
        coverImage: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 7-14 يوم عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "custom-analytics" },
      update: {},
      create: {
        title: "لوحات تحليلات مخصصة",
        slug: "custom-analytics",
        shortDesc: "تحليلات مخصصة لمقاييس الأعمال وKPIs",
        description: "نبني تحليلاتك: custom dashboard، data integration، KPI tracking، reports، insights",
        price: 1800,
        oldPrice: 3000,
        coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 5-10 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "social-media-automation" },
      update: {},
      create: {
        title: "أتمتة السوشيال ميديا",
        slug: "social-media-automation",
        shortDesc: "أدوات أتمتة للنشر والتواصل في السوشيال ميديا",
        description: "نؤتمت سوشيالك: automation tools، scheduling، content management، analytics، engagement",
        price: 1000,
        oldPrice: 1800,
        coverImage: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 3-7 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "payment-integration" },
      update: {},
      create: {
        title: "تكامل بوابات الدفع",
        slug: "payment-integration",
        shortDesc: "ربط بوابات الدفع وأنظمة الفواتير",
        description: "نكامل الدفع: payment gateways، billing system، security، subscriptions، notifications",
        price: 1500,
        oldPrice: 2500,
        coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 5-10 أيام عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "ai-writing-assistant" },
      update: {},
      create: {
        title: "مساعد كتابة بالذكاء الاصطناعي",
        slug: "ai-writing-assistant",
        shortDesc: "أدوات كتابة مخصصة بالذكاء الاصطناعي للصناعات المختلفة",
        description: "نبني أداة الكتابة: writing tool، AI integration، templates، industry-specific، optimization",
        price: 2000,
        oldPrice: 3500,
        coverImage: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 7-14 يوم عمل",
      },
    }),
    prisma.product.upsert({
      where: { slug: "technical-consulting" },
      update: {},
      create: {
        title: "استشارات تقنية ومراجعة أنظمة",
        slug: "technical-consulting",
        shortDesc: "استشارات تقنية متخصصة ومراجعة شاملة للأنظمة",
        description: "نستشير تقنياً: system audit، recommendations، implementation plan، support، training",
        price: 1500,
        oldPrice: 2500,
        coverImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
        status: "active",
        featured: false,
        purchaseType: "contact",
        categoryId: catServices.id,
        deliveryNote: "التسليم خلال 2-5 أيام عمل",
      },
    }),
  ]);
  console.log("✅ تم إنشاء المنتجات");

  // Blog categories
  const [catDev, catDesign, catBusiness] = await Promise.all([
    prisma.blogCategory.upsert({
      where: { slug: "development" },
      update: {},
      create: { name: "تطوير", slug: "development" },
    }),
    prisma.blogCategory.upsert({
      where: { slug: "design" },
      update: {},
      create: { name: "تصميم", slug: "design" },
    }),
    prisma.blogCategory.upsert({
      where: { slug: "business" },
      update: {},
      create: { name: "بزنس", slug: "business" },
    }),
  ]);
  console.log("✅ تم إنشاء تصنيفات المدونة");

  // Blog posts
  await Promise.all([
    prisma.blogPost.upsert({
      where: { slug: "nextjs-14-complete-guide" },
      update: {},
      create: {
        title: "الدليل الشامل لـ Next.js 14: كل ما تحتاج معرفته",
        slug: "nextjs-14-complete-guide",
        excerpt: "استكشف أهم مميزات Next.js 14 من Server Components إلى App Router مع أمثلة عملية",
        content: "<p>يُعدّ Next.js 14 من أقوى الأطر البرمجية لبناء تطبيقات الويب الحديثة. في هذا الدليل الشامل نستعرض أبرز المميزات الجديدة.</p>",
        coverImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200",
        status: "published",
        featured: true,
        tags: JSON.stringify(["nextjs", "react", "javascript"]),
        categoryId: catDev.id,
        publishedAt: new Date(),
        readTime: 8,
      },
    }),
    prisma.blogPost.upsert({
      where: { slug: "tailwindcss-tips-arabic" },
      update: {},
      create: {
        title: "20 نصيحة Tailwind CSS ستغير طريقة عملك للأبد",
        slug: "tailwindcss-tips-arabic",
        excerpt: "نصائح وحيل احترافية في Tailwind CSS لتسريع تطوير واجهات المستخدم",
        content: "<p>Tailwind CSS ثورة حقيقية في عالم تصميم الويب. هذه النصائح ستجعلك خبيراً.</p>",
        coverImage: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=1200",
        status: "published",
        featured: true,
        tags: JSON.stringify(["tailwind", "css", "تصميم"]),
        categoryId: catDesign.id,
        publishedAt: new Date(),
        readTime: 6,
      },
    }),
    prisma.blogPost.upsert({
      where: { slug: "freelancing-egypt-guide" },
      update: {},
      create: {
        title: "دليل الفريلانس في مصر 2024: من الصفر إلى الاحتراف",
        slug: "freelancing-egypt-guide",
        excerpt: "كيف تبدأ مشوارك كمستقل في مصر وتحقق دخلاً بالدولار",
        content: "<p>الفريلانس أصبح من أكثر المجالات نمواً في مصر والوطن العربي. دليلنا الشامل يوضح كل خطوة.</p>",
        coverImage: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200",
        status: "published",
        featured: false,
        tags: JSON.stringify(["فريلانس", "بزنس", "مصر"]),
        categoryId: catBusiness.id,
        publishedAt: new Date(),
        readTime: 12,
      },
    }),
  ]);
  console.log("✅ تم إنشاء مقالات المدونة");

  // Portfolio projects
  await Promise.all([
    prisma.portfolioProject.upsert({
      where: { slug: "abud-ecommerce" },
      update: {},
      create: {
        title: "ABUD E-Commerce Platform",
        slug: "abud-ecommerce",
        description: "منصة تجارة إلكترونية متكاملة بـ Next.js 14 و Stripe و Prisma مع لوحة تحكم متقدمة",
        thumbnail: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200",
        featured: true,
        tags: JSON.stringify(["Next.js", "TypeScript", "Prisma", "Stripe", "Tailwind"]),
        links: JSON.stringify(["https://github.com/abud", "https://abud-store.vercel.app"]),
      },
    }),
    prisma.portfolioProject.upsert({
      where: { slug: "arabic-dashboard-ui" },
      update: {},
      create: {
        title: "Arabic Admin Dashboard UI",
        slug: "arabic-dashboard-ui",
        description: "لوحة تحكم إدارية عربية الأولى بتصميم RTL كامل وتجربة مستخدم احترافية",
        thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200",
        featured: true,
        tags: JSON.stringify(["React", "Tailwind CSS", "RTL", "TypeScript"]),
        links: JSON.stringify(["https://github.com/abud/dashboard"]),
      },
    }),
    prisma.portfolioProject.upsert({
      where: { slug: "ai-content-generator" },
      update: {},
      create: {
        title: "AI Arabic Content Generator",
        slug: "ai-content-generator",
        description: "تطبيق لتوليد محتوى عربي احترافي باستخدام OpenAI GPT-4 و Langchain",
        thumbnail: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1200",
        featured: false,
        tags: JSON.stringify(["OpenAI", "Langchain", "Python", "FastAPI"]),
        links: JSON.stringify(["https://github.com/abud/ai-gen"]),
      },
    }),
  ]);
  console.log("✅ تم إنشاء مشاريع البورتفوليو");

  // Services
  await Promise.all([
    prisma.service.upsert({
      where: { slug: "web-development" },
      update: {},
      create: {
        title: "تطوير مواقع وتطبيقات الويب",
        slug: "web-development",
        description: "نبني لك موقع أو تطبيق ويب احترافي بأحدث التقنيات مع ضمان الأداء والسرعة",
        longDesc: "تصميم UI/UX احترافي — متوافق مع الجوال — سريع وآمن — لوحة تحكم كاملة — دعم فني شهر",
        icon: "🌐",
        priceType: "fixed",
        price: 2000,
        ctaLabel: "يبدأ من",
        featured: true,
        isActive: true,
        order: 1,
      },
    }),
    prisma.service.upsert({
      where: { slug: "ui-ux-design" },
      update: {},
      create: {
        title: "تصميم UI/UX",
        slug: "ui-ux-design",
        description: "نصمم تجارب مستخدم استثنائية تزيد من معدلات التحويل وتبهر عملاءك",
        longDesc: "تصميم Figma احترافي — نماذج تفاعلية — تصميم RTL عربي — ملفات قابلة للتعديل",
        icon: "🎨",
        priceType: "fixed",
        price: 800,
        ctaLabel: "يبدأ من",
        featured: true,
        isActive: true,
        order: 2,
      },
    }),
    prisma.service.upsert({
      where: { slug: "ecommerce-store" },
      update: {},
      create: {
        title: "إنشاء متجر إلكتروني",
        slug: "ecommerce-store",
        description: "نبني متجرك الإلكتروني الاحترافي مع بوابات الدفع والإدارة الكاملة",
        longDesc: "تصميم متجر — بوابات دفع متعددة — إدارة المنتجات والطلبات — دعم فني 3 أشهر",
        icon: "🛍️",
        priceType: "fixed",
        price: 3500,
        ctaLabel: "يبدأ من",
        featured: false,
        isActive: true,
        order: 3,
      },
    }),
    prisma.service.upsert({
      where: { slug: "technical-consultation" },
      update: {},
      create: {
        title: "استشارات تقنية",
        slug: "technical-consultation",
        description: "جلسات استشارية فردية لمساعدتك في اختيار التقنية المناسبة وبناء فريقك",
        longDesc: "جلسة ساعة — مراجعة الكود — معمارية النظام — خطة عمل تقنية",
        icon: "💡",
        priceType: "hourly",
        price: 300,
        ctaLabel: "للجلسة",
        featured: false,
        isActive: true,
        order: 4,
      },
    }),
  ]);
  console.log("✅ تم إنشاء الخدمات");

  // Site settings
  const siteSettingsData = [
    { key: "site_title", value: "ABUD Platform" },
    { key: "site_description", value: "منصة رقمية متكاملة للمطورين والمصممين العرب" },
    { key: "site_email", value: "contact@abud.com" },
    { key: "site_phone", value: "+20 100 000 0000" },
    { key: "whatsapp_number", value: "+20 100 000 0000" },
    { key: "social_twitter", value: "https://x.com/abud" },
    { key: "social_github", value: "https://github.com/abud" },
  ];

  for (const s of siteSettingsData) {
    await prisma.siteSetting.upsert({
      where: { key: s.key },
      update: { value: s.value },
      create: s,
    });
  }
  console.log("✅ تم إنشاء إعدادات الموقع");

  // Payment settings
  await Promise.all([
    prisma.paymentSetting.upsert({
      where: { method: "vodafone_cash" },
      update: {},
      create: {
        method: "vodafone_cash",
        label: "فودافون كاش",
        isActive: true,
        destination: "01000000000",
        instructions: "قم بتحويل المبلغ على رقم فودافون كاش المذكور، ثم ارفع صورة من إيصال التحويل.",
      },
    }),
    prisma.paymentSetting.upsert({
      where: { method: "instapay" },
      update: {},
      create: {
        method: "instapay",
        label: "إنستاباي",
        isActive: true,
        destination: "abud@instapay",
        instructions: "قم بالتحويل على InstaPay باستخدام الـ IPA المذكور، ثم ارفع إيصال التحويل.",
      },
    }),
    prisma.paymentSetting.upsert({
      where: { method: "paypal" },
      update: {},
      create: {
        method: "paypal",
        label: "PayPal",
        isActive: false,
        destination: "payments@abud.com",
        instructions: "قم بالدفع عبر PayPal على البريد المذكور كـ Friends & Family.",
      },
    }),
  ]);
  console.log("✅ تم إنشاء إعدادات الدفع");

  console.log("\n🎉 تمت عملية التهيئة بنجاح!");
  console.log("📧 البريد الإداري: admin@abud.com");
  console.log("🔑 كلمة المرور: admin123456");
  console.log("⚠️  يُرجى تغيير كلمة المرور بعد أول تسجيل دخول");
}

main()
  .catch((e) => {
    console.error("❌ خطأ في التهيئة:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
