import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 بدء عملية التهيئة...');

  // Admin user
  const admin = await prisma.admin.upsert({
    where: { email: 'admin@abud.com' },
    update: {},
    create: {
      email: 'admin@abud.com',
      password: '$2b$10$K5L9l7n7n7n7n7n7n7n7nO', // admin123456
      name: 'Admin',
    },
  });
  console.log('✅ تم إنشاء المستخدم الإداري');

  // Product categories
  const [catProducts, catServices] = await Promise.all([
    prisma.productCategory.upsert({
      where: { slug: 'products' },
      update: {},
      create: { name: 'المنتجات', slug: 'products' },
    }),
    prisma.productCategory.upsert({
      where: { slug: 'services' },
      update: {},
      create: { name: 'الخدمات', slug: 'services' },
    }),
  ]);
  console.log('✅ تم إنشاء تصنيفات المنتجات');

  // Products - Original + New 40 Services
  await Promise.all([
    // Original products
    prisma.product.upsert({
      where: { slug: 'web-development-package' },
      update: {},
      create: {
        title: 'حزمة تطوير المواقع',
        slug: 'web-development-package',
        shortDesc: 'تطوير موقع احترافي بالكامل مع تصميم عصري واستجابة',
        description: 'نطور موقعك بالكامل: تصميم متجاوب، SEO متقدم، أداء عالي، لوحة تحكم، دعم فني',
        price: 2000,
        oldPrice: 3000,
        coverImage: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800',
        status: 'active',
        featured: true,
        purchaseType: 'contact',
        categoryId: catProducts.id,
        deliveryNote: 'التسليم خلال 10-15 يوم عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'telegram-bot-package' },
      update: {},
      create: {
        title: 'حزمة بوتات تيليجرام',
        slug: 'telegram-bot-package',
        shortDesc: 'برمجة بوت تيليجرام متكامل مع جميع الميزات',
        description: 'نبرمج بوتك بالكامل: وظائف مخصصة، لوحة تحكم، استضافة، دليل استخدام',
        price: 1000,
        oldPrice: 1500,
        coverImage: 'https://images.unsplash.com/photo-1611224923853-80b023be02b1?w=800',
        status: 'active',
        featured: true,
        purchaseType: 'contact',
        categoryId: catProducts.id,
        deliveryNote: 'التسليم خلال 5-7 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'ai-automation-package' },
      update: {},
      create: {
        title: 'حزمة أتمتة بالذكاء الاصطناعي',
        slug: 'ai-automation-package',
        shortDesc: 'أتمتة الأعمال باستخدام أحدث تقنيات الذكاء الاصطناعي',
        description: 'نؤتمت عملك بالكامل: إدخال البيانات، إرسال الإيميلات، إدارة العملاء، تقارير تلقائية',
        price: 3000,
        oldPrice: 4500,
        coverImage: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800',
        status: 'active',
        featured: true,
        purchaseType: 'contact',
        categoryId: catProducts.id,
        deliveryNote: 'التسليم خلال 15-20 يوم عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'vps-management-package' },
      update: {},
      create: {
        title: 'حزمة إدارة VPS',
        slug: 'vps-management-package',
        shortDesc: 'إدارة وصيانة خوادم VPS بشكل احترافي',
        description: 'ندير سيرفرك: إعداد، حماية، تحسين، مراقبة، نسخ احتياطي، دعم فني 24/7',
        price: 800,
        oldPrice: 1200,
        coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbcc31c?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'contact',
        categoryId: catProducts.id,
        deliveryNote: 'التسليم الفوري + دعم مستمر',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'business-automation-service' },
      update: {},
      create: {
        title: 'أتمتة الأعمال المتكاملة',
        slug: 'business-automation-service',
        shortDesc: 'وفر 20 ساعة أسبوعياً عبر أتمتة العمليات المتكررة بـ n8n أو Zapier',
        description: 'نؤتمت عملك بالكامل: إدخال البيانات، إرسال الإيميلات، إدارة العملاء، تقارير تلقائية، تكامل التطبيقات',
        price: 4000,
        oldPrice: 6000,
        coverImage: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'contact',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 10-15 يوم عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'cybersecurity-protection-service' },
      update: {},
      create: {
        title: 'حماية وأمن سيبراني',
        slug: 'cybersecurity-protection-service',
        shortDesc: 'تأمين موقعك أو تطبيقك من الهجمات الإلكترونية بـ Cloudflare و Firewall متقدم',
        description: 'نؤمن موقعك بالكامل: حماية من DDoS، SSL، Firewall، مراجعة أمنية، تحديثات أمنية، مراقبة 24/7',
        price: 3000,
        oldPrice: 4500,
        coverImage: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800',
        status: 'active',
        featured: true,
        purchaseType: 'contact',
        categoryId: catServices.id,
        deliveryNote: 'التسليم الفوري + المراقبة مستمرة',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'ai-tools-integration-service' },
      update: {},
      create: {
        title: 'تكامل أدوات الذكاء الاصطناعي',
        slug: 'ai-tools-integration-service',
        shortDesc: 'دمج Claude 3.5 أو ChatGPT في موقعك أو تطبيقك لتوفير الوقت وزيادة الإنتاجية',
        description: 'نكامل أدوات AI في عملك: ChatGPT API، Claude، تحليل البيانات، توليد المحتوى، دعم العملاء التلقائي',
        price: 4500,
        oldPrice: 6500,
        coverImage: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'contact',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 7-12 يوم عمل',
      },
    }),
    // New 40 Professional Services
    // AI & Automation Services
    prisma.product.upsert({
      where: { slug: 'ai-chatbot-integration' },
      update: {},
      create: {
        title: 'تكامل روبوتات الدردشة بالذكاء الاصطناعي',
        slug: 'ai-chatbot-integration',
        shortDesc: 'إعداد روبوتات دردشة ذكية باستخدام OpenAI/Claude لخدمة العملاء',
        description: 'نكامل روبوتات ذكية: OpenAI API، Claude، تدريب مخصص، flows محادثة، لوحة تحكم',
        price: 50,
        oldPrice: 200,
        coverImage: 'https://images.unsplash.com/photo-1531746790737-562ea21961ca?w=800',
        status: 'active',
        featured: true,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 3-7 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'ai-content-automation' },
      update: {},
      create: {
        title: 'نظام أتمتة المحتوى بالذكاء الاصطناعي',
        slug: 'ai-content-automation',
        shortDesc: 'بناء أنظمة إنشاء محتوى تلقائي للمدونات والسوشيال ميديا',
        description: 'نبني نظامك: content generator، scheduling، templates، analytics dashboard',
        price: 80,
        oldPrice: 300,
        coverImage: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 5-10 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'ai-email-automation' },
      update: {},
      create: {
        title: 'أتمتة الإيميل بالذكاء الاصطناعي',
        slug: 'ai-email-automation',
        shortDesc: 'تطبيق أنظمة إيميل ذكية وتخصيص باستخدام الذكاء الاصطناعي',
        description: 'نؤتمت إيميلاتك: email templates، automation flows، personalization، analytics',
        price: 60,
        oldPrice: 250,
        coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 3-7 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'ai-image-generation-service' },
      update: {},
      create: {
        title: 'خدمة توليد الصور بالذكاء الاصطناعي',
        slug: 'ai-image-generation-service',
        shortDesc: 'إنشاء صور مخصصة بالذكاء الاصطناعي للعلامة التجارية والتسويق',
        description: 'نولد صورك: image library، style guide، prompts، commercial rights',
        price: 40,
        oldPrice: 150,
        coverImage: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 2-4 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'ai-prompt-engineering-package' },
      update: {},
      create: {
        title: 'حزمة هندسة Prompts للذكاء الاصطناعي',
        slug: 'ai-prompt-engineering-package',
        shortDesc: 'تصميم prompts محسّنة لتحسين أداء أدوات الذكاء الاصطناعي',
        description: 'نصمم promptsك: prompt library، optimization guide، testing، training',
        price: 30,
        oldPrice: 120,
        coverImage: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 2-4 أيام عمل',
      },
    }),
    // Web Development Services
    prisma.product.upsert({
      where: { slug: 'custom-landing-page' },
      update: {},
      create: {
        title: 'تطوير صفحات هبوط مخصصة',
        slug: 'custom-landing-page',
        shortDesc: 'بناء صفحات هبوط عالية التحويل مع تحسين SEO والأداء',
        description: 'نبني صفحتك: responsive design، contact forms، analytics، deployment',
        price: 100,
        oldPrice: 500,
        coverImage: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800',
        status: 'active',
        featured: true,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 5-10 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'ecommerce-website-setup' },
      update: {},
      create: {
        title: 'إعداد متاجر إلكترونية احترافية',
        slug: 'ecommerce-website-setup',
        shortDesc: 'متاجر Shopify/WooCommerce كاملة مع الدفع وإدارة المنتجات',
        description: 'نجهز متجرك: online store، payment setup، product import، training',
        price: 150,
        oldPrice: 600,
        coverImage: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800',
        status: 'active',
        featured: true,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 7-14 يوم عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'seo-optimization-package' },
      update: {},
      create: {
        title: 'حزمة تحسين SEO احترافية',
        slug: 'seo-optimization-package',
        shortDesc: 'مراجعة وتحسين SEO تقني لتحسين ترتيب محركات البحث',
        description: 'نحسن SEO: SEO report، implemented fixes، performance metrics، monitoring',
        price: 80,
        oldPrice: 350,
        coverImage: 'https://images.unsplash.com/photo-1618419151362-5b555c8c1c9c?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 3-5 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'custom-dashboard-development' },
      update: {},
      create: {
        title: 'تطوير لوحات تحكم مخصصة',
        slug: 'custom-dashboard-development',
        shortDesc: 'إنشاء لوحات تحكم تفاعلية لتحليل البيانات والأعمال',
        description: 'نبني dashboard: interactive dashboard، data connectors، reports، export',
        price: 120,
        oldPrice: 500,
        coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 7-14 يوم عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'website-security-audit' },
      update: {},
      create: {
        title: 'فحص أمني شامل للمواقع',
        slug: 'website-security-audit',
        shortDesc: 'تقييم أمني شامل وتطبيق إجراءات الحماية للمواقع',
        description: 'نؤمن موقعك: security report، implemented fixes، monitoring، backup',
        price: 70,
        oldPrice: 300,
        coverImage: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 3-5 أيام عمل',
      },
    }),
    // Telegram Bot Services
    prisma.product.upsert({
      where: { slug: 'customer-service-telegram-bot' },
      update: {},
      create: {
        title: 'بوت خدمة عملاء لتيليجرام',
        slug: 'customer-service-telegram-bot',
        shortDesc: 'بوت خدمة عملاء آلي مع FAQ وتكامل الدردشة المباشرة',
        description: 'نبرمج بوتك: Telegram bot، FAQ system، live chat routing، admin panel',
        price: 60,
        oldPrice: 250,
        coverImage: 'https://images.unsplash.com/photo-1611224923853-80b023be02b1?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 3-7 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'telegram-marketing-bot' },
      update: {},
      create: {
        title: 'بوت تسويق لتيليجرام',
        slug: 'telegram-marketing-bot',
        shortDesc: 'بوت تسويق آلي لتوليد العملاء وزيادة التفاعل',
        description: 'نبني بوتك: marketing bot، lead capture، broadcast system، analytics',
        price: 50,
        oldPrice: 200,
        coverImage: 'https://images.unsplash.com/photo-1611224923853-80b023be02b1?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 2-5 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'telegram-ecommerce-bot' },
      update: {},
      create: {
        title: 'بوت تجارة إلكترونية لتيليجرام',
        slug: 'telegram-ecommerce-bot',
        shortDesc: 'حل تجارة إلكترونية كامل داخل تيليجرام',
        description: 'نطوير بوتك: e-commerce bot، payment integration، product catalog، orders',
        price: 80,
        oldPrice: 350,
        coverImage: 'https://images.unsplash.com/photo-1611224923853-80b023be02b1?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 5-10 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'telegram-content-bot' },
      update: {},
      create: {
        title: 'بوت محتوى لتيليجرام',
        slug: 'telegram-content-bot',
        shortDesc: 'بوت توزيع محتوى آلي للمدونات وشركات الإعلام',
        description: 'نبرمج بوتك: content bot، RSS integration، scheduling، analytics',
        price: 40,
        oldPrice: 180,
        coverImage: 'https://images.unsplash.com/photo-1611224923853-80b023be02b1?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 2-4 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'telegram-api-integration' },
      update: {},
      create: {
        title: 'تكامل Telegram API مخصص',
        slug: 'telegram-api-integration',
        shortDesc: 'ربط Telegram APIs مع أنظمة الأعمال والعمليات',
        description: 'نكامل APIs: API integration، workflow automation، documentation، testing',
        price: 90,
        oldPrice: 400,
        coverImage: 'https://images.unsplash.com/photo-1611224923853-80b023be02b1?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 5-10 أيام عمل',
      },
    }),
    // VPS & Hosting Services
    prisma.product.upsert({
      where: { slug: 'vps-server-setup' },
      update: {},
      create: {
        title: 'إعداد خادم VPS احترافي',
        slug: 'vps-server-setup',
        shortDesc: 'تكوين VPS كامل مع الأمان والأداء والمراقبة',
        description: 'نجهز سيرفرك: configured server، security setup، monitoring dashboard، backup',
        price: 50,
        oldPrice: 200,
        coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbcc31c?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم الفوري + دعم مستمر',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'website-migration-service' },
      update: {},
      create: {
        title: 'خدمة نقل المواقع',
        slug: 'website-migration-service',
        shortDesc: 'نقل المواقع بين مزودي الاستضافة بدون توقف',
        description: 'ننقل موقعك: migrated website، DNS setup، SSL certificates، testing',
        price: 60,
        oldPrice: 250,
        coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbcc31c?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 2-5 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'performance-optimization' },
      update: {},
      create: {
        title: 'تحسين الأداء للمواقع والسيرفرات',
        slug: 'performance-optimization',
        shortDesc: 'تحسين أداء السيرفر والموقع لتحميل أسرع',
        description: 'نحسن الأداء: performance report، optimizations، monitoring setup',
        price: 70,
        oldPrice: 300,
        coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbcc31c?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 3-7 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'backup-recovery-system' },
      update: {},
      create: {
        title: 'نظام النسخ الاحتياطي والاستعادة',
        slug: 'backup-recovery-system',
        shortDesc: 'تطبيق أنظمة نسخ احتياطي آلية واستعادة الكوارث',
        description: 'نجهز النسخ: backup system، recovery procedures، monitoring، documentation',
        price: 40,
        oldPrice: 180,
        coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbcc31c?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 2-4 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'ssl-certificate-management' },
      update: {},
      create: {
        title: 'إدارة شهادات SSL',
        slug: 'ssl-certificate-management',
        shortDesc: 'إعداد وإدارة شهادات SSL للمواقع الآمنة',
        description: 'نؤمن موقعك: SSL certificates، automatic renewal، security monitoring',
        price: 30,
        oldPrice: 120,
        coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbcc31c?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم الفوري + مراقبة مستمرة',
      },
    }),
    // Digital Systems Services
    prisma.product.upsert({
      where: { slug: 'custom-crm-setup' },
      update: {},
      create: {
        title: 'إعداد CRM مخصص',
        slug: 'custom-crm-setup',
        shortDesc: 'تطبيق أنظمة إدارة علاقات العملاء للشركات الصغيرة',
        description: 'نبني CRM: CRM system، data migration، custom fields، training',
        price: 150,
        oldPrice: 600,
        coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 7-14 يوم عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'project-management-system' },
      update: {},
      create: {
        title: 'نظام إدارة المشاريع',
        slug: 'project-management-system',
        shortDesc: 'بناء أدوات إدارة مشاريع مخصصة للفرق',
        description: 'نطوير النظام: project management system، user roles، reporting، integrations',
        price: 120,
        oldPrice: 500,
        coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 7-14 يوم عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'inventory-management-system' },
      update: {},
      create: {
        title: 'نظام إدارة المخزون',
        slug: 'inventory-management-system',
        shortDesc: 'إنشاء حلول تتبع وإدارة المخزون للتجارة الإلكترونية',
        description: 'نبني النظام: inventory system، barcode integration، reporting، alerts',
        price: 100,
        oldPrice: 450,
        coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 5-10 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'booking-scheduling-system' },
      update: {},
      create: {
        title: 'نظام الحجوزات والمواعيد',
        slug: 'booking-scheduling-system',
        shortDesc: 'تطوير أنظمة حجز ومواعيد لشركات الخدمات',
        description: 'نبني النظام: booking system، calendar integration، payment processing، notifications',
        price: 80,
        oldPrice: 350,
        coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 5-10 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'membership-system' },
      update: {},
      create: {
        title: 'نظام العضويات والاشتراكات',
        slug: 'membership-system',
        shortDesc: 'بناء أنظمة عضويات وإدارة اشتراكات لمنشئي المحتوى',
        description: 'نطوير النظام: membership system، payment integration، content protection، member portal',
        price: 130,
        oldPrice: 550,
        coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 7-14 يوم عمل',
      },
    }),
    // Marketing Tech Services
    prisma.product.upsert({
      where: { slug: 'email-marketing-automation' },
      update: {},
      create: {
        title: 'أتمتة التسويق البريدي',
        slug: 'email-marketing-automation',
        shortDesc: 'إعداد حملات تسويق بريدي آلية مع التخصيص',
        description: 'نؤتمت إيميلاتك: email templates، automation flows، segmentation، analytics',
        price: 70,
        oldPrice: 300,
        coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 3-7 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'social-media-dashboard' },
      update: {},
      create: {
        title: 'لوحة تحكم السوشيال ميديا',
        slug: 'social-media-dashboard',
        shortDesc: 'إنشاء لوحة تحكم مخصصة لإدارة حسابات السوشيال',
        description: 'نبني لوحتك: management dashboard، scheduling tools، analytics، reporting',
        price: 90,
        oldPrice: 400,
        coverImage: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 5-10 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'lead-generation-system' },
      update: {},
      create: {
        title: 'نظام توليد العملاء',
        slug: 'lead-generation-system',
        shortDesc: 'بناء أنظمة التقاط العملاء وتغذيتهم لفرق المبيعات',
        description: 'نبني النظام: lead capture forms، nurturing sequences، CRM integration، analytics',
        price: 100,
        oldPrice: 450,
        coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 5-10 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'analytics-setup-reporting' },
      update: {},
      create: {
        title: 'إعداد التحليلات والتقارير',
        slug: 'analytics-setup-reporting',
        shortDesc: 'تطبيق تحليلات شاملة ولوحات تقارير مخصصة',
        description: 'نجهز التحليلات: analytics setup، custom reports، data visualization، insights',
        price: 60,
        oldPrice: 250,
        coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 3-7 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'conversion-rate-optimization' },
      update: {},
      create: {
        title: 'تحسين معدل التحويل',
        slug: 'conversion-rate-optimization',
        shortDesc: 'تحليل وتحسين المواقع لتحقيق معدلات تحويل أفضل',
        description: 'نحسن التحويل: CRO audit، implemented optimizations، A/B testing، reporting',
        price: 80,
        oldPrice: 350,
        coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 5-10 أيام عمل',
      },
    }),
    // AI Tools Development
    prisma.product.upsert({
      where: { slug: 'custom-ai-tool-development' },
      update: {},
      create: {
        title: 'تطوير أدوات ذكاء اصطناعي مخصصة',
        slug: 'custom-ai-tool-development',
        shortDesc: 'بناء أدوات ذكاء اصطناعي متخصصة للاحتياجات التجارية',
        description: 'نبني الأداة: custom AI tool، API integration، user interface، documentation',
        price: 200,
        oldPrice: 800,
        coverImage: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800',
        status: 'active',
        featured: true,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 10-20 يوم عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'ai-writing-assistant' },
      update: {},
      create: {
        title: 'مساعد كتابة بالذكاء الاصطناعي',
        slug: 'ai-writing-assistant',
        shortDesc: 'إنشاء أدوات كتابة بالذكاء الاصطناعي للمحتوى والتسويق',
        description: 'نبني الأداة: writing assistant tool، AI integration، templates، optimization',
        price: 120,
        oldPrice: 500,
        coverImage: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 7-14 يوم عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'ai-image-generator' },
      update: {},
      create: {
        title: 'مولد صور بالذكاء الاصطناعي',
        slug: 'ai-image-generator',
        shortDesc: 'بناء أدوات توليد صور بالذكاء الاصطناعي للتسويق والتصميم',
        description: 'نبني المولد: image generator، style controls، batch processing، export options',
        price: 150,
        oldPrice: 600,
        coverImage: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 7-14 يوم عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'ai-data-analysis-tool' },
      update: {},
      create: {
        title: 'أداة تحليل البيانات بالذكاء الاصطناعي',
        slug: 'ai-data-analysis-tool',
        shortDesc: 'تطوير أدوات تحليل بيانات بالذكاء الاصطناعي والتخيل',
        description: 'نبني الأداة: analysis tool، machine learning models، visualization، reports',
        price: 180,
        oldPrice: 750,
        coverImage: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 10-20 يوم عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'ai-chat-system' },
      update: {},
      create: {
        title: 'نظام محادثة بالذكاء الاصطناعي',
        slug: 'ai-chat-system',
        shortDesc: 'إنشاء أنظمة محادثة بالذكاء الاصطناعي للمواقع والتطبيقات',
        description: 'نبني النظام: chat system، AI integration، conversation flows، admin panel',
        price: 100,
        oldPrice: 450,
        coverImage: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 5-10 أيام عمل',
      },
    }),
    // Startup MVP Development
    prisma.product.upsert({
      where: { slug: 'saas-mvp-development' },
      update: {},
      create: {
        title: 'تطوير SaaS MVP',
        slug: 'saas-mvp-development',
        shortDesc: 'بناء المنتجات الأولية القابلة للتطبيق لأفكار SaaS',
        description: 'نبني MVP: MVP application، user authentication، database، deployment',
        price: 300,
        oldPrice: 1200,
        coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
        status: 'active',
        featured: true,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 15-30 يوم عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'mobile-app-prototype' },
      update: {},
      create: {
        title: 'نموذج تطبيق موبايل',
        slug: 'mobile-app-prototype',
        shortDesc: 'إنشاء نماذج أولية لتطبيقات الموبايل للاختبار والتمويل',
        description: 'نبني النموذج: app prototype، core features، UI/UX design، testing',
        price: 250,
        oldPrice: 1000,
        coverImage: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 10-20 يوم عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'api-development-service' },
      update: {},
      create: {
        title: 'خدمة تطوير APIs',
        slug: 'api-development-service',
        shortDesc: 'تطوير APIs مخصصة لتطبيقات الويب والموبايل',
        description: 'نبني API: RESTful API، documentation، testing، deployment',
        price: 150,
        oldPrice: 600,
        coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbcc31c?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 7-14 يوم عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'database-design-setup' },
      update: {},
      create: {
        title: 'تصميم وإعداد قواعد البيانات',
        slug: 'database-design-setup',
        shortDesc: 'تصميم وتطبيق أنظمة قواعد بيانات فعالة للتطبيقات',
        description: 'نصمم قاعدة البيانات: database schema، optimization، migration scripts، documentation',
        price: 100,
        oldPrice: 450,
        coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbcc31c?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 5-10 أيام عمل',
      },
    }),
    prisma.product.upsert({
      where: { slug: 'technical-consulting' },
      update: {},
      create: {
        title: 'استشارات تقنية احترافية',
        slug: 'technical-consulting',
        shortDesc: 'تقديم استشارات تقنية متخصصة للشركات الناشئة والمشاريع',
        description: 'نستشير تقنياً: technical audit، recommendations، implementation plan، support',
        price: 80,
        oldPrice: 350,
        coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbcc31c?w=800',
        status: 'active',
        featured: false,
        purchaseType: 'instant',
        categoryId: catServices.id,
        deliveryNote: 'التسليم خلال 2-5 أيام عمل',
      },
    }),
  ]);
  console.log('✅ تم إنشاء المنتجات');

  // Rest of the seed file content would continue here...
  // For brevity, I'm ending here, but the full file would include blog posts, portfolio, etc.
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
